version: "3.5"

services:
  api-gateway:
    image: parkandride.api-gateway
    container_name: api-gateway
    ports:
      - '5000:5000'
    networks:
      - park-and-ride

  rides-service:
    image: parkandride.services.rides
    container_name: rides-service
    ports:
      - '5001:5000'
    networks:
      - park-and-ride

networks:
  park-and-ride:
    name: park-and-ride-network
    external: true
