version: "3.5"

services:
    mongo:
        image: mongo:4
        container_name: mongo
        ports:
            - 27017:27017
        networks:
            - park-and-ride
        volumes:
        - mongo:/data/dbMongo

networks:
  park-and-ride:
    name: park-and-ride-network

volumes:
  mongo:
    driver: local