version: "3.5"

services:
    mongo:
        image: mongo:4
        container_name: mongo
        ports:
            - 27017:27017
        networks:
            - park-and-ride
        volumes:
        - mongo:/data/dbMongo

     rabbitmq:
        image: rabbitmq:3
        container_name: rabbitmq
        ports:
        - 5672:5672
         - 15672:15672
         networks:
         - park-and-ride
        volumes: 
         - rabbitmq:/var/lib/rabbitmq

networks:
  park-and-ride:
    name: park-and-ride-network

volumes:
  mongo:
    driver: local
  rabbitmq:
    driver: local